#!/usr/bin/env node
/**
 * Build step: read data/ → produce two artifacts the Angular app consumes.
 *
 *   1. app/src/data/index.ts
 *      A TypeScript module exporting strongly-typed, eagerly-loaded
 *      arrays/maps. Used at prerender time so every page can render
 *      to static HTML without a runtime fetch.
 *
 *   2. app/public/data/
 *      A copy of all canonical JSON files, served as static assets.
 *      Used at runtime for incremental research updates (pattern/<id>/research/*)
 *      without rebuilding the bundle.
 *
 * Run this before `ng build` / `ng serve`. The npm scripts in app/package.json
 * wire it as a `prebuild`/`prestart` step.
 */

import {
  readFileSync, writeFileSync, mkdirSync,
  readdirSync, statSync, existsSync, rmSync, copyFileSync,
} from 'node:fs';
import { join, dirname, resolve, relative } from 'node:path';
import { fileURLToPath } from 'node:url';

const __dirname = dirname(fileURLToPath(import.meta.url));
const ROOT      = resolve(__dirname, '..');
const DATA      = join(ROOT, 'data');
const APP       = join(ROOT, 'app');
const OUT_TS    = join(APP, 'src', 'data');
const OUT_ASSET = join(APP, 'public', 'data');

/* ─────────────────── helpers ─────────────────── */

function readJson(absPath) {
  return JSON.parse(readFileSync(absPath, 'utf8'));
}

function listDirs(absPath) {
  if (!existsSync(absPath)) return [];
  return readdirSync(absPath)
    .filter(name => !name.startsWith('_') && statSync(join(absPath, name)).isDirectory())
    .sort();
}

function copyTree(srcDir, destDir) {
  if (!existsSync(srcDir)) return;
  mkdirSync(destDir, { recursive: true });
  for (const entry of readdirSync(srcDir)) {
    const src  = join(srcDir, entry);
    const dest = join(destDir, entry);
    const st   = statSync(src);
    if (st.isDirectory()) copyTree(src, dest);
    else copyFileSync(src, dest);
  }
}

/* ─────────────────── load ─────────────────── */

console.log('Loading data/…');

const patterns   = listDirs(join(DATA, 'patterns'))
  .map(id => readJson(join(DATA, 'patterns', id, 'pattern.json')));

const categories = listDirs(join(DATA, 'categories'))
  .map(id => readJson(join(DATA, 'categories', id, 'category.json')));

const concepts   = listDirs(join(DATA, 'concepts'))
  .map(id => {
    const concept = readJson(join(DATA, 'concepts', id, 'concept.json'));
    const articlePath = join(DATA, 'concepts', id, 'article.json');
    return existsSync(articlePath)
      ? { ...concept, has_article: true }
      : { ...concept, has_article: false };
  });

const tools      = listDirs(join(DATA, 'tools'))
  .map(id => readJson(join(DATA, 'tools', id, 'tool.json')));

const sources    = listDirs(join(DATA, 'sources'))
  .map(id => readJson(join(DATA, 'sources', id, 'source.json')));

const toolKinds  = readJson(join(DATA, '_meta', 'tool-kinds.json'));
const radarMeta  = readJson(join(DATA, '_meta', 'radar.json'));

/* ─────────────────── cross-reference check ─────────────────── */

const patternIds = new Set(patterns.map(p => p.id));
const categoryIds = new Set(categories.map(c => c.id));
const conceptIds = new Set(concepts.map(c => c.id));
const errors = [];

for (const p of patterns) {
  if (!categoryIds.has(p.category)) {
    errors.push(`pattern ${p.id} references missing category ${p.category}`);
  }
}
for (const c of concepts) {
  for (const ref of c.patterns) {
    if (!patternIds.has(ref)) errors.push(`concept ${c.id} references missing pattern ${ref}`);
  }
}
for (const t of tools) {
  for (const ref of t.patterns) {
    if (!patternIds.has(ref)) errors.push(`tool ${t.id} references missing pattern ${ref}`);
  }
}
for (const s of sources) {
  for (const ref of s.patterns) {
    if (!patternIds.has(ref)) errors.push(`source ${s.id} references missing pattern ${ref}`);
  }
}
if (errors.length) {
  console.error('\nCross-reference errors:');
  for (const e of errors) console.error(`  ${e}`);
  process.exit(1);
}

/* ─────────────────── emit TS module ─────────────────── */

mkdirSync(OUT_TS, { recursive: true });

const typesSource = `// AUTO-GENERATED by scripts/build-data.mjs — do not edit by hand.

export type PatternClassify = 'new' | 'intensified' | 'proven' | 'trial' | 'assess' | 'anti-pattern' | 'unknown';
export type PatternLayer    = 'operating' | 'infra';

export interface Pattern {
  id: string;
  num: string;
  category: string;
  layer: PatternLayer;
  classify: PatternClassify;
  title: string;
  one_liner: string;
  problem: string;
  solution: string;
  keywords: string[];
}

export interface Category {
  id: string;
  num: string;
  color: string;
  name: string;
  tagline: string;
  blurb: string;
}

export interface Concept {
  id: string;
  term: string;
  short: string;
  patterns: string[];
  has_article: boolean;
}

export interface Tool {
  id: string;
  name: string;
  vendor: string;
  kind: string;
  blurb: string;
  url: string;
  oss_url: string | null;
  patterns: string[];
}

export interface Source {
  id: string;
  title: string;
  author: string;
  kind: 'post' | 'doc' | 'paper' | 'video' | 'book' | 'other';
  url: string;
  patterns: string[];
}

export interface ToolKind {
  id: string;
  label: string;
  intro: string;
}

export type RadarRingId = 'adopt' | 'trial' | 'assess' | 'hold';
export interface RadarRing {
  id:    RadarRingId;
  label: string;
  color: string;
  hint:  string;
}
export interface RadarMeta {
  rings:        readonly RadarRing[];
  sector_short: Readonly<Record<string, string>>;
  positions:    Readonly<Record<string, RadarRingId>>;
}
`;

writeFileSync(join(OUT_TS, 'types.ts'), typesSource);

const indexSource = `// AUTO-GENERATED by scripts/build-data.mjs — do not edit by hand.

import type { Pattern, Category, Concept, Tool, Source, ToolKind, RadarMeta, RadarRingId } from './types';

export const PATTERNS:   readonly Pattern[]   = ${JSON.stringify(patterns,   null, 2)} as const;
export const CATEGORIES: readonly Category[]  = ${JSON.stringify(categories, null, 2)} as const;
export const CONCEPTS:   readonly Concept[]   = ${JSON.stringify(concepts,   null, 2)} as const;
export const TOOLS:      readonly Tool[]      = ${JSON.stringify(tools,      null, 2)} as const;
export const SOURCES:    readonly Source[]    = ${JSON.stringify(sources,    null, 2)} as const;
export const TOOL_KINDS: readonly ToolKind[]  = ${JSON.stringify(toolKinds,  null, 2)} as const;
export const RADAR:      RadarMeta            = ${JSON.stringify(radarMeta,  null, 2)} as const;

export const PATTERN_BY_ID:   ReadonlyMap<string, Pattern>  = new Map(PATTERNS.map(p => [p.id, p]));
export const CATEGORY_BY_ID:  ReadonlyMap<string, Category> = new Map(CATEGORIES.map(c => [c.id, c]));
export const CONCEPT_BY_ID:   ReadonlyMap<string, Concept>  = new Map(CONCEPTS.map(c => [c.id, c]));
export const TOOL_BY_ID:      ReadonlyMap<string, Tool>     = new Map(TOOLS.map(t => [t.id, t]));
export const SOURCE_BY_ID:    ReadonlyMap<string, Source>   = new Map(SOURCES.map(s => [s.id, s]));

/** Curated radar position for a pattern, falling back to the classify-derived ring. */
export function radarRingOf(p: Pattern): RadarRingId {
  const curated = RADAR.positions[p.id];
  if (curated) return curated;
  if (p.classify === 'anti-pattern') return 'hold';
  if (p.classify === 'proven')       return 'adopt';
  if (p.classify === 'intensified')  return 'trial';
  return 'assess';
}

export type { Pattern, Category, Concept, Tool, Source, ToolKind, RadarMeta, RadarRingId, RadarRing } from './types';
`;

writeFileSync(join(OUT_TS, 'index.ts'), indexSource);
console.log(`  wrote ${relative(ROOT, join(OUT_TS, 'index.ts'))}`);

/* ─────────────────── copy assets ─────────────────── */

if (existsSync(OUT_ASSET)) rmSync(OUT_ASSET, { recursive: true, force: true });
for (const sub of ['patterns', 'categories', 'concepts', 'tools', 'sources', '_meta']) {
  copyTree(join(DATA, sub), join(OUT_ASSET, sub));
}
console.log(`  copied data tree → ${relative(ROOT, OUT_ASSET)}`);

console.log('\nSummary:');
console.log(`  ${patterns.length} patterns, ${categories.length} categories, ${concepts.length} concepts, ${tools.length} tools, ${sources.length} sources`);
